;; Quail packages for inputting Cyrillic characters.
;; Copyright (C) 1992 Free Software Foundation, Inc.
;; This file is part of Mule (MULtilingual Enhancement of GNU Emacs).

;; Mule is free software distributed in the form of patches to GNU Emacs.
;; You can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 1, or (at your option)
;; any later version.

;; Mule is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs; see the file COPYING.  If not, write to
;; the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.

;;; 92.7.14   created for Mule Ver.0.9.5 by Takahashi N. <ntakahas@etl.go.jp>
;;; 92.9.8    modified by Takahashi N. <ntakahas@etl.go.jp>
;;; 92.11.25  modified by Takahashi N. <ntakahas@etl.go.jp>
;;; 92.12.28  modified by Takahashi N. <ntakahas@etl.go.jp>
;;;           Macedonian, Serbian & Byelorussian are added
;;; 93.4.22   modified by Takahashi N. <ntakahas@etl.go.jp>
;;;           added "jis-russian".

(require 'quail)

(quail-define-package "jcuken" ",L9FC:5=" nil "Cyrillic (ISO 8859-5) encoding.

They say this layout is widely used in Russia." nil t t t t)

;;  1! 2@ 3# 4" 5: 6, 7. 8* 9( 0) -_ =+ ,L!
;;   ,L9  ,LF  ,LC  ,L:  ,L5  ,L=  ,L3  ,LH  ,LI  ,L7  ,LE  ,Lj
;;    ,LD  ,LK  ,L2  ,L0  ,L?  ,L@  ,L>  ,L;  ,L4  ,L6  ,LM
;;     ,LO  ,LG  ,LA  ,L<  ,L8  ,LB  ,LL  ,L1  ,LN  /?

(quail-defrule "1" ?1)
(quail-defrule "2" ?2)
(quail-defrule "3" ?3)
(quail-defrule "4" ?4)
(quail-defrule "5" ?5)
(quail-defrule "6" ?6)
(quail-defrule "7" ?7)
(quail-defrule "8" ?8)
(quail-defrule "9" ?9)
(quail-defrule "0" ?0)
(quail-defrule "-" ?-)
(quail-defrule "=" ?=)
(quail-defrule "`" ?,Lq)
(quail-defrule "q" ?,LY)
(quail-defrule "w" ?,Lf)
(quail-defrule "e" ?,Lc)
(quail-defrule "r" ?,LZ)
(quail-defrule "t" ?,LU)
(quail-defrule "y" ?,L])
(quail-defrule "u" ?,LS)
(quail-defrule "i" ?,Lh)
(quail-defrule "o" ?,Li)
(quail-defrule "p" ?,LW)
(quail-defrule "[" ?,Le)
(quail-defrule "]" ?,Lj)
(quail-defrule "a" ?,Ld)
(quail-defrule "s" ?,Lk)
(quail-defrule "d" ?,LR)
(quail-defrule "f" ?,LP)
(quail-defrule "g" ?,L_)
(quail-defrule "h" ?,L`)
(quail-defrule "j" ?,L^)
(quail-defrule "k" ?,L[)
(quail-defrule "l" ?,LT)
(quail-defrule ";" ?,LV)
(quail-defrule "'" ?,Lm)
(quail-defrule "\\" ?\\)
(quail-defrule "z" ?,Lo)
(quail-defrule "x" ?,Lg)
(quail-defrule "c" ?,La)
(quail-defrule "v" ?,L\)
(quail-defrule "b" ?,LX)
(quail-defrule "n" ?,Lb)
(quail-defrule "m" ?,Ll)
(quail-defrule "," ?,LQ)
(quail-defrule "." ?,Ln)
(quail-defrule "/" ?/)

(quail-defrule "!" ?!)
(quail-defrule "@" ?@)
(quail-defrule "#" ?#)
(quail-defrule "$" ?\")
(quail-defrule "%" ?:)
(quail-defrule "^" ?,)
(quail-defrule "&" ?.)
(quail-defrule "*" ?*)
(quail-defrule "(" ?()
(quail-defrule ")" ?))
(quail-defrule "_" ?_)
(quail-defrule "+" ?+)
(quail-defrule "~" ?,L!)
(quail-defrule "Q" ?,L9)
(quail-defrule "W" ?,LF)
(quail-defrule "E" ?,LC)
(quail-defrule "R" ?,L:)
(quail-defrule "T" ?,L5)
(quail-defrule "Y" ?,L=)
(quail-defrule "U" ?,L3)
(quail-defrule "I" ?,LH)
(quail-defrule "O" ?,LI)
(quail-defrule "P" ?,L7)
(quail-defrule "{" ?,LE)
(quail-defrule "}" ?,LJ)
(quail-defrule "A" ?,LD)
(quail-defrule "S" ?,LK)
(quail-defrule "D" ?,L2)
(quail-defrule "F" ?,L0)
(quail-defrule "G" ?,L?)
(quail-defrule "H" ?,L@)
(quail-defrule "J" ?,L>)
(quail-defrule "K" ?,L;)
(quail-defrule "L" ?,L4)
(quail-defrule ":" ?,L6)
(quail-defrule "\"" ?,LM)
(quail-defrule "|" ?|)
(quail-defrule "Z" ?,LO)
(quail-defrule "X" ?,LG)
(quail-defrule "C" ?,LA)
(quail-defrule "V" ?,L<)
(quail-defrule "B" ?,L8)
(quail-defrule "N" ?,LB)
(quail-defrule "M" ?,LL)
(quail-defrule "<" ?,L1)
(quail-defrule ">" ?,LN)
(quail-defrule "?" ??)

;;

(quail-define-package "jis-ruassian" "ЙЦУКЕН" nil
		      "JIS X0208.1983 encoding.

The layout is same as jcuken, but uses JIS characters." nil t t t t)

;;  1! 2@ 3# 4" 5: 6, 7. 8* 9( 0) -_ =+ ,L!
;;   ,L9  ,LF  ,LC  ,L:  ,L5  ,L=  ,L3  ,LH  ,LI  ,L7  ,LE  ,Lj
;;    ,LD  ,LK  ,L2  ,L0  ,L?  ,L@  ,L>  ,L;  ,L4  ,L6  ,LM
;;     ,LO  ,LG  ,LA  ,L<  ,L8  ,LB  ,LL  ,L1  ,LN  /?

(quail-defrule "1" ?１)
(quail-defrule "2" ?２)
(quail-defrule "3" ?３)
(quail-defrule "4" ?４)
(quail-defrule "5" ?５)
(quail-defrule "6" ?６)
(quail-defrule "7" ?７)
(quail-defrule "8" ?８)
(quail-defrule "9" ?９)
(quail-defrule "0" ?０)
(quail-defrule "-" ?−)
(quail-defrule "=" ?＝)
(quail-defrule "`" ?ё)
(quail-defrule "q" ?й)
(quail-defrule "w" ?ц)
(quail-defrule "e" ?у)
(quail-defrule "r" ?к)
(quail-defrule "t" ?е)
(quail-defrule "y" ?н)
(quail-defrule "u" ?г)
(quail-defrule "i" ?ш)
(quail-defrule "o" ?щ)
(quail-defrule "p" ?з)
(quail-defrule "[" ?х)
(quail-defrule "]" ?ъ)
(quail-defrule "a" ?ф)
(quail-defrule "s" ?ы)
(quail-defrule "d" ?в)
(quail-defrule "f" ?а)
(quail-defrule "g" ?п)
(quail-defrule "h" ?р)
(quail-defrule "j" ?о)
(quail-defrule "k" ?л)
(quail-defrule "l" ?д)
(quail-defrule ";" ?ж)
(quail-defrule "'" ?э)
(quail-defrule "\\" ?＼)
(quail-defrule "z" ?я)
(quail-defrule "x" ?ч)
(quail-defrule "c" ?с)
(quail-defrule "v" ?м)
(quail-defrule "b" ?и)
(quail-defrule "n" ?т)
(quail-defrule "m" ?ь)
(quail-defrule "," ?б)
(quail-defrule "." ?ю)
(quail-defrule "/" ?／)

(quail-defrule "!" ?！)
(quail-defrule "@" ?＠)
(quail-defrule "#" ?＃)
(quail-defrule "$" ?”)
(quail-defrule "%" ?：)
(quail-defrule "^" ?，)
(quail-defrule "&" ?．)
(quail-defrule "*" ?＊)
(quail-defrule "(" ?（)
(quail-defrule ")" ?）)
(quail-defrule "_" ?＿)
(quail-defrule "+" ?＋)
(quail-defrule "~" ?Ё)
(quail-defrule "Q" ?Й)
(quail-defrule "W" ?Ц)
(quail-defrule "E" ?У)
(quail-defrule "R" ?К)
(quail-defrule "T" ?Е)
(quail-defrule "Y" ?Н)
(quail-defrule "U" ?Г)
(quail-defrule "I" ?Ш)
(quail-defrule "O" ?Щ)
(quail-defrule "P" ?З)
(quail-defrule "{" ?Х)
(quail-defrule "}" ?Ъ)
(quail-defrule "A" ?Ф)
(quail-defrule "S" ?Ы)
(quail-defrule "D" ?В)
(quail-defrule "F" ?А)
(quail-defrule "G" ?П)
(quail-defrule "H" ?Р)
(quail-defrule "J" ?О)
(quail-defrule "K" ?Л)
(quail-defrule "L" ?Д)
(quail-defrule ":" ?Ж)
(quail-defrule "\"" ?Э)
(quail-defrule "|" ?｜)
(quail-defrule "Z" ?Я)
(quail-defrule "X" ?Ч)
(quail-defrule "C" ?С)
(quail-defrule "V" ?М)
(quail-defrule "B" ?И)
(quail-defrule "N" ?Т)
(quail-defrule "M" ?Ь)
(quail-defrule "<" ?Б)
(quail-defrule ">" ?Ю)
(quail-defrule "?" ?？)

;;

(quail-define-package "macedonian" ",L)*5@B7-,L#," nil
  "Cyrillic (ISO 8859-5) encoding.

This layout is based on JUS.I.K1.004." nil t t t t)

;;  1! 2" 3# 4$ 5% 6& 7' 8( 9) 0= /? +* <>
;;   ,L)  ,L*  ,L5  ,L@  ,LB  ,L7  ,LC  ,L8  ,L>  ,L?  ,LH  ,L#
;;    ,L0  ,LA  ,L4  ,LD  ,L3  ,LE  ,L(  ,L:  ,L;  ,LG  ,L,  ,L6
;;     ,L%  ,L/  ,LF  ,L2  ,L1  ,L=  ,L<  ,; .: -_

(quail-defrule "1" ?1)
(quail-defrule "2" ?2)
(quail-defrule "3" ?3)
(quail-defrule "4" ?4)
(quail-defrule "5" ?5)
(quail-defrule "6" ?6)
(quail-defrule "7" ?7)
(quail-defrule "8" ?8)
(quail-defrule "9" ?9)
(quail-defrule "0" ?0)
(quail-defrule "-" ?/)
(quail-defrule "=" ?+)
(quail-defrule "`" ?<)
(quail-defrule "q" ?,Ly)
(quail-defrule "w" ?,Lz)
(quail-defrule "e" ?,LU)
(quail-defrule "r" ?,L`)
(quail-defrule "t" ?,Lb)
(quail-defrule "y" ?,LW)
(quail-defrule "u" ?,Lc)
(quail-defrule "i" ?,LX)
(quail-defrule "o" ?,L^)
(quail-defrule "p" ?,L_)
(quail-defrule "[" ?,Lh)
(quail-defrule "]" ?,Ls)
(quail-defrule "a" ?,LP)
(quail-defrule "s" ?,La)
(quail-defrule "d" ?,LT)
(quail-defrule "f" ?,Ld)
(quail-defrule "g" ?,LS)
(quail-defrule "h" ?,Le)
(quail-defrule "j" ?,Lx)
(quail-defrule "k" ?,LZ)
(quail-defrule "l" ?,L[)
(quail-defrule ";" ?,Lg)
(quail-defrule "'" ?,L|)
(quail-defrule "\\" ?,LV)
(quail-defrule "z" ?,Lu)
(quail-defrule "x" ?,L)
(quail-defrule "c" ?,Lf)
(quail-defrule "v" ?,LR)
(quail-defrule "b" ?,LQ)
(quail-defrule "n" ?,L])
(quail-defrule "m" ?,L\)
(quail-defrule "," ?,)
(quail-defrule "." ?.)
(quail-defrule "/" ?-)

(quail-defrule "!" ?!)
(quail-defrule "@" ?\")
(quail-defrule "#" ?#)
(quail-defrule "$" ?$)
(quail-defrule "%" ?%)
(quail-defrule "^" ?&)
(quail-defrule "&" ?')
(quail-defrule "*" ?()
(quail-defrule "(" ?))
(quail-defrule ")" ?=)
(quail-defrule "_" ??)
(quail-defrule "+" ?*)
(quail-defrule "~" ?>)
(quail-defrule "Q" ?,L))
(quail-defrule "W" ?,L*)
(quail-defrule "E" ?,L5)
(quail-defrule "R" ?,L@)
(quail-defrule "T" ?,LB)
(quail-defrule "Y" ?,L7)
(quail-defrule "U" ?,LC)
(quail-defrule "I" ?,L8)
(quail-defrule "O" ?,L>)
(quail-defrule "P" ?,L?)
(quail-defrule "{" ?,LH)
(quail-defrule "}" ?,L#)
(quail-defrule "A" ?,L0)
(quail-defrule "S" ?,LA)
(quail-defrule "D" ?,L4)
(quail-defrule "F" ?,LD)
(quail-defrule "G" ?,L3)
(quail-defrule "H" ?,LE)
(quail-defrule "J" ?,L()
(quail-defrule "K" ?,L:)
(quail-defrule "L" ?,L;)
(quail-defrule ":" ?,LG)
(quail-defrule "\"" ?,L,)
(quail-defrule "|" ?,L6)
(quail-defrule "Z" ?,L%)
(quail-defrule "X" ?,L/)
(quail-defrule "C" ?,LF)
(quail-defrule "V" ?,L2)
(quail-defrule "B" ?,L1)
(quail-defrule "N" ?,L=)
(quail-defrule "M" ?,L<)
(quail-defrule "<" ?;)
(quail-defrule ">" ?:)
(quail-defrule "?" ?_)

;;

(quail-define-package "serbian" ",L)*5@B7-,L"+" nil
  "Cyrillic (ISO 8859-5) encoding.

This layout is based on JUS.I.K1.005." nil t t t t)

;;  1! 2" 3# 4$ 5% 6& 7' 8( 9) 0= /? +* <>
;;   ,L)  ,L*  ,L5  ,L@  ,LB  ,L7  ,LC  ,L8  ,L>  ,L?  ,LH  ,L"
;;    ,L0  ,LA  ,L4  ,LD  ,L3  ,LE  ,L(  ,L:  ,L;  ,LG  ,L+  ,L6
;;     ,L%  ,L/  ,LF  ,L2  ,L1  ,L=  ,L<  ,; .: -_

(quail-defrule "1" ?1)
(quail-defrule "2" ?2)
(quail-defrule "3" ?3)
(quail-defrule "4" ?4)
(quail-defrule "5" ?5)
(quail-defrule "6" ?6)
(quail-defrule "7" ?7)
(quail-defrule "8" ?8)
(quail-defrule "9" ?9)
(quail-defrule "0" ?0)
(quail-defrule "-" ?/)
(quail-defrule "=" ?+)
(quail-defrule "`" ?<)
(quail-defrule "q" ?,Ly)
(quail-defrule "w" ?,Lz)
(quail-defrule "e" ?,LU)
(quail-defrule "r" ?,L`)
(quail-defrule "t" ?,Lb)
(quail-defrule "y" ?,LW)
(quail-defrule "u" ?,Lc)
(quail-defrule "i" ?,LX)
(quail-defrule "o" ?,L^)
(quail-defrule "p" ?,L_)
(quail-defrule "[" ?,Lh)
(quail-defrule "]" ?,Lr)
(quail-defrule "a" ?,LP)
(quail-defrule "s" ?,La)
(quail-defrule "d" ?,LT)
(quail-defrule "f" ?,Ld)
(quail-defrule "g" ?,LS)
(quail-defrule "h" ?,Le)
(quail-defrule "j" ?,Lx)
(quail-defrule "k" ?,LZ)
(quail-defrule "l" ?,L[)
(quail-defrule ";" ?,Lg)
(quail-defrule "'" ?,L{)
(quail-defrule "\\" ?,LV)
(quail-defrule "z" ?,Lu)
(quail-defrule "x" ?,L)
(quail-defrule "c" ?,Lf)
(quail-defrule "v" ?,LR)
(quail-defrule "b" ?,LQ)
(quail-defrule "n" ?,L])
(quail-defrule "m" ?,L\)
(quail-defrule "," ?,)
(quail-defrule "." ?.)
(quail-defrule "/" ?-)

(quail-defrule "!" ?!)
(quail-defrule "@" ?\")
(quail-defrule "#" ?#)
(quail-defrule "$" ?$)
(quail-defrule "%" ?%)
(quail-defrule "^" ?&)
(quail-defrule "&" ?')
(quail-defrule "*" ?()
(quail-defrule "(" ?))
(quail-defrule ")" ?=)
(quail-defrule "_" ??)
(quail-defrule "+" ?*)
(quail-defrule "~" ?>)
(quail-defrule "Q" ?,L))
(quail-defrule "W" ?,L*)
(quail-defrule "E" ?,L5)
(quail-defrule "R" ?,L@)
(quail-defrule "T" ?,LB)
(quail-defrule "Y" ?,L7)
(quail-defrule "U" ?,LC)
(quail-defrule "I" ?,L8)
(quail-defrule "O" ?,L>)
(quail-defrule "P" ?,L?)
(quail-defrule "{" ?,LH)
(quail-defrule "}" ?,L")
(quail-defrule "A" ?,L0)
(quail-defrule "S" ?,LA)
(quail-defrule "D" ?,L4)
(quail-defrule "F" ?,LD)
(quail-defrule "G" ?,L3)
(quail-defrule "H" ?,LE)
(quail-defrule "J" ?,L()
(quail-defrule "K" ?,L:)
(quail-defrule "L" ?,L;)
(quail-defrule ":" ?,LG)
(quail-defrule "\"" ?,L+)
(quail-defrule "|" ?,L6)
(quail-defrule "Z" ?,L%)
(quail-defrule "X" ?,L/)
(quail-defrule "C" ?,LF)
(quail-defrule "V" ?,L2)
(quail-defrule "B" ?,L1)
(quail-defrule "N" ?,L=)
(quail-defrule "M" ?,L<)
(quail-defrule "<" ?;)
(quail-defrule ">" ?:)
(quail-defrule "?" ?_)

;;

(quail-define-package "beylorussian" ",L)*5@B7-,L&." nil
  "Cyrillic (ISO 8859-5) encoding." nil t t t t)

;;  1! 2" 3# 4$ 5% 6& 7' 8( 9) 0= /? +* <>
;;   ,L)  ,L*  ,L5  ,L@  ,LB  ,L7  ,LC  ,L8  ,L>  ,L?  ,LH  ,L&
;;    ,L0  ,LA  ,L4  ,LD  ,L3  ,LE  ,L(  ,L:  ,L;  ,LG  ,L.  ,L6
;;     ,L%  ,L/  ,LF  ,L2  ,L1  ,L=  ,L<  ,; .: -_

(quail-defrule "1" ?1)
(quail-defrule "2" ?2)
(quail-defrule "3" ?3)
(quail-defrule "4" ?4)
(quail-defrule "5" ?5)
(quail-defrule "6" ?6)
(quail-defrule "7" ?7)
(quail-defrule "8" ?8)
(quail-defrule "9" ?9)
(quail-defrule "0" ?0)
(quail-defrule "-" ?/)
(quail-defrule "=" ?+)
(quail-defrule "`" ?<)
(quail-defrule "q" ?,Ly)
(quail-defrule "w" ?,Lz)
(quail-defrule "e" ?,LU)
(quail-defrule "r" ?,L`)
(quail-defrule "t" ?,Lb)
(quail-defrule "y" ?,LW)
(quail-defrule "u" ?,Lc)
(quail-defrule "i" ?,LX)
(quail-defrule "o" ?,L^)
(quail-defrule "p" ?,L_)
(quail-defrule "[" ?,Lh)
(quail-defrule "]" ?,Lv)
(quail-defrule "a" ?,LP)
(quail-defrule "s" ?,La)
(quail-defrule "d" ?,LT)
(quail-defrule "f" ?,Ld)
(quail-defrule "g" ?,LS)
(quail-defrule "h" ?,Le)
(quail-defrule "j" ?,Lx)
(quail-defrule "k" ?,LZ)
(quail-defrule "l" ?,L[)
(quail-defrule ";" ?,Lg)
(quail-defrule "'" ?,L~)
(quail-defrule "\\" ?,LV)
(quail-defrule "z" ?,Lu)
(quail-defrule "x" ?,L)
(quail-defrule "c" ?,Lf)
(quail-defrule "v" ?,LR)
(quail-defrule "b" ?,LQ)
(quail-defrule "n" ?,L])
(quail-defrule "m" ?,L\)
(quail-defrule "," ?,)
(quail-defrule "." ?.)
(quail-defrule "/" ?-)

(quail-defrule "!" ?!)
(quail-defrule "@" ?\")
(quail-defrule "#" ?#)
(quail-defrule "$" ?$)
(quail-defrule "%" ?%)
(quail-defrule "^" ?&)
(quail-defrule "&" ?')
(quail-defrule "*" ?()
(quail-defrule "(" ?))
(quail-defrule ")" ?=)
(quail-defrule "_" ??)
(quail-defrule "+" ?*)
(quail-defrule "~" ?>)
(quail-defrule "Q" ?,L))
(quail-defrule "W" ?,L*)
(quail-defrule "E" ?,L5)
(quail-defrule "R" ?,L@)
(quail-defrule "T" ?,LB)
(quail-defrule "Y" ?,L7)
(quail-defrule "U" ?,LC)
(quail-defrule "I" ?,L8)
(quail-defrule "O" ?,L>)
(quail-defrule "P" ?,L?)
(quail-defrule "{" ?,LH)
(quail-defrule "}" ?,L&)
(quail-defrule "A" ?,L0)
(quail-defrule "S" ?,LA)
(quail-defrule "D" ?,L4)
(quail-defrule "F" ?,LD)
(quail-defrule "G" ?,L3)
(quail-defrule "H" ?,LE)
(quail-defrule "J" ?,L()
(quail-defrule "K" ?,L:)
(quail-defrule "L" ?,L;)
(quail-defrule ":" ?,LG)
(quail-defrule "\"" ?,L.)
(quail-defrule "|" ?,L6)
(quail-defrule "Z" ?,L%)
(quail-defrule "X" ?,L/)
(quail-defrule "C" ?,LF)
(quail-defrule "V" ?,L2)
(quail-defrule "B" ?,L1)
(quail-defrule "N" ?,L=)
(quail-defrule "M" ?,L<)
(quail-defrule "<" ?;)
(quail-defrule ">" ?:)
(quail-defrule "?" ?_)

;;

(quail-define-package "ukrainian" ",L$'5@B7-,L&." nil
  "Cyrillic (ISO 8859-5) encoding.

Sorry, but 'ghe with upturn' is not included in ISO 8859-5" nil t t t t)

;;  1! 2" 3# 4$ 5% 6& 7' 8( 9) 0= /? +* <>
;;   ,L$  ,L'  ,L5  ,L@  ,LB  ,L7  ,LC  ,L8  ,L>  ,L?  ,LH  ,L&
;;    ,L0  ,LA  ,L4  ,LD  ,L3  ,LE  ,L(  ,L:  ,L;  ,LG  ,L.  ,L6
;;     ,L%  ,L/  ,LF  ,L2  ,L1  ,L=  ,L<  ,; .: -_

(quail-defrule "1" ?1)
(quail-defrule "2" ?2)
(quail-defrule "3" ?3)
(quail-defrule "4" ?4)
(quail-defrule "5" ?5)
(quail-defrule "6" ?6)
(quail-defrule "7" ?7)
(quail-defrule "8" ?8)
(quail-defrule "9" ?9)
(quail-defrule "0" ?0)
(quail-defrule "-" ?/)
(quail-defrule "=" ?+)
(quail-defrule "`" ?<)
(quail-defrule "q" ?,Lt)
(quail-defrule "w" ?,Lw)
(quail-defrule "e" ?,LU)
(quail-defrule "r" ?,L`)
(quail-defrule "t" ?,Lb)
(quail-defrule "y" ?,LW)
(quail-defrule "u" ?,Lc)
(quail-defrule "i" ?,LX)
(quail-defrule "o" ?,L^)
(quail-defrule "p" ?,L_)
(quail-defrule "[" ?,Lh)
(quail-defrule "]" ?,Lv)
(quail-defrule "a" ?,LP)
(quail-defrule "s" ?,La)
(quail-defrule "d" ?,LT)
(quail-defrule "f" ?,Ld)
(quail-defrule "g" ?,LS)
(quail-defrule "h" ?,Le)
(quail-defrule "j" ?,Lx)
(quail-defrule "k" ?,LZ)
(quail-defrule "l" ?,L[)
(quail-defrule ";" ?,Lg)
(quail-defrule "'" ?,L~)
(quail-defrule "\\" ?,LV)
(quail-defrule "z" ?,Lu)
(quail-defrule "x" ?,L)
(quail-defrule "c" ?,Lf)
(quail-defrule "v" ?,LR)
(quail-defrule "b" ?,LQ)
(quail-defrule "n" ?,L])
(quail-defrule "m" ?,L\)
(quail-defrule "," ?,)
(quail-defrule "." ?.)
(quail-defrule "/" ?-)

(quail-defrule "!" ?!)
(quail-defrule "@" ?\")
(quail-defrule "#" ?#)
(quail-defrule "$" ?$)
(quail-defrule "%" ?%)
(quail-defrule "^" ?&)
(quail-defrule "&" ?')
(quail-defrule "*" ?()
(quail-defrule "(" ?))
(quail-defrule ")" ?=)
(quail-defrule "_" ??)
(quail-defrule "+" ?*)
(quail-defrule "~" ?>)
(quail-defrule "Q" ?,L$)
(quail-defrule "W" ?,L')
(quail-defrule "E" ?,L5)
(quail-defrule "R" ?,L@)
(quail-defrule "T" ?,LB)
(quail-defrule "Y" ?,L7)
(quail-defrule "U" ?,LC)
(quail-defrule "I" ?,L8)
(quail-defrule "O" ?,L>)
(quail-defrule "P" ?,L?)
(quail-defrule "{" ?,LH)
(quail-defrule "}" ?,L&)
(quail-defrule "A" ?,L0)
(quail-defrule "S" ?,LA)
(quail-defrule "D" ?,L4)
(quail-defrule "F" ?,LD)
(quail-defrule "G" ?,L3)
(quail-defrule "H" ?,LE)
(quail-defrule "J" ?,L()
(quail-defrule "K" ?,L:)
(quail-defrule "L" ?,L;)
(quail-defrule ":" ?,LG)
(quail-defrule "\"" ?,L.)
(quail-defrule "|" ?,L6)
(quail-defrule "Z" ?,L%)
(quail-defrule "X" ?,L/)
(quail-defrule "C" ?,LF)
(quail-defrule "V" ?,L2)
(quail-defrule "B" ?,L1)
(quail-defrule "N" ?,L=)
(quail-defrule "M" ?,L<)
(quail-defrule "<" ?;)
(quail-defrule ">" ?:)
(quail-defrule "?" ?_)

;;

(quail-define-package "yawerty" ",LO25@BK" nil "Cyrillic (ISO 8859-5) encoding.

This layout is based on Roman transcription.
When preceded by a '/', the second and the third rows (number key row) change
as follows.

  keytop | Q  W  E  R  T  Y  U  I  O  P  A  S  D
 --------+---------------------------------------
  input  | ,L"  ,L#  ,L$  ,L%  ,L&  ,L'  ,L(  ,L)  ,L*  ,L+  ,L,  ,L.  ,L/
" nil t t t t)

;;  1! 2,Lq 3,Lj 4,L! 5% 6^ 7& 8* 9( 0) -_ ,LG  ,LN
;;   ,LO  ,L2  ,L5  ,L@  ,LB  ,LK  ,LC  ,L8  ,L>  ,L?  ,LH  ,LI
;;    ,L0  ,LA  ,L4  ,LD  ,L3  ,LE  ,L9  ,L:  ,L;  ;: '" ,LM
;;     ,L7  ,LL  ,LF  ,L6  ,L1  ,L=  ,L<  ,< .> /?

;;  1! 2,Lq 3,Lj 4,L! 5% 6^ 7& 8* 9( 0) -_ ,LG  ,LN
;;   ,L"  ,L#  ,L$  ,L%  ,L&  ,L'  ,L(  ,L)  ,L*  ,L+  ,LH  ,LI
;;    ,L,  ,L.  ,L/  ,LD  ,L3  ,LE  ,L9  ,L:  ,L;  ;: '" ,LM
;;     ,L7  ,LL  ,LF  ,L6  ,L1  ,L=  ,L<  ,< .> /?

(quail-defrule "1" ?1)
(quail-defrule "2" ?2)
(quail-defrule "3" ?3)
(quail-defrule "4" ?4)
(quail-defrule "5" ?5)
(quail-defrule "6" ?6)
(quail-defrule "7" ?7)
(quail-defrule "8" ?8)
(quail-defrule "9" ?9)
(quail-defrule "0" ?0)
(quail-defrule "-" ?-)
(quail-defrule "=" ?,Lg)
(quail-defrule "`" ?,Ln)
(quail-defrule "q" ?,Lo)
(quail-defrule "w" ?,LR)
(quail-defrule "e" ?,LU)
(quail-defrule "r" ?,L`)
(quail-defrule "t" ?,Lb)
(quail-defrule "y" ?,Lk)
(quail-defrule "u" ?,Lc)
(quail-defrule "i" ?,LX)
(quail-defrule "o" ?,L^)
(quail-defrule "p" ?,L_)
(quail-defrule "[" ?,Lh)
(quail-defrule "]" ?,Li)
(quail-defrule "a" ?,LP)
(quail-defrule "s" ?,La)
(quail-defrule "d" ?,LT)
(quail-defrule "f" ?,Ld)
(quail-defrule "g" ?,LS)
(quail-defrule "h" ?,Le)
(quail-defrule "j" ?,LY)
(quail-defrule "k" ?,LZ)
(quail-defrule "l" ?,L[)
(quail-defrule ";" ?;)
(quail-defrule "'" ?')
(quail-defrule "\\" ?,Lm)
(quail-defrule "z" ?,LW)
(quail-defrule "x" ?,Ll)
(quail-defrule "c" ?,Lf)
(quail-defrule "v" ?,LV)
(quail-defrule "b" ?,LQ)
(quail-defrule "n" ?,L])
(quail-defrule "m" ?,L\)
(quail-defrule "," ?,)
(quail-defrule "." ?.)
(quail-defrule "/" ?/)

(quail-defrule "!" ?!)
(quail-defrule "@" ?,Lq)
(quail-defrule "#" ?,Lj)
(quail-defrule "$" ?,L!)
(quail-defrule "%" ?%)
(quail-defrule "^" ?^)
(quail-defrule "&" ?&)
(quail-defrule "*" ?*)
(quail-defrule "(" ?()
(quail-defrule ")" ?))
(quail-defrule "_" ?_)
(quail-defrule "+" ?,LG)
(quail-defrule "~" ?,LN)
(quail-defrule "Q" ?,LO)
(quail-defrule "W" ?,L2)
(quail-defrule "E" ?,L5)
(quail-defrule "R" ?,L@)
(quail-defrule "T" ?,LB)
(quail-defrule "Y" ?,LK)
(quail-defrule "U" ?,LC)
(quail-defrule "I" ?,L8)
(quail-defrule "O" ?,L>)
(quail-defrule "P" ?,L?)
(quail-defrule "{" ?,LH)
(quail-defrule "}" ?,LI)
(quail-defrule "A" ?,L0)
(quail-defrule "S" ?,LA)
(quail-defrule "D" ?,L4)
(quail-defrule "F" ?,LD)
(quail-defrule "G" ?,L3)
(quail-defrule "H" ?,LE)
(quail-defrule "J" ?,L9)
(quail-defrule "K" ?,L:)
(quail-defrule "L" ?,L;)
(quail-defrule ":" ?:)
(quail-defrule "\"" ?\")
(quail-defrule "|" ?,LM)
(quail-defrule "Z" ?,L7)
(quail-defrule "X" ?,LL)
(quail-defrule "C" ?,LF)
(quail-defrule "V" ?,L6)
(quail-defrule "B" ?,L1)
(quail-defrule "N" ?,L=)
(quail-defrule "M" ?,L<)
(quail-defrule "<" ?<)
(quail-defrule ">" ?>)
(quail-defrule "?" ??)

(quail-defrule "/q" ?,Lr)
(quail-defrule "/w" ?,Ls)
(quail-defrule "/e" ?,Lt)
(quail-defrule "/r" ?,Lu)
(quail-defrule "/t" ?,Lv)
(quail-defrule "/y" ?,Lw)
(quail-defrule "/u" ?,Lx)
(quail-defrule "/i" ?,Ly)
(quail-defrule "/o" ?,Lz)
(quail-defrule "/p" ?,L{)
(quail-defrule "/a" ?,L|)
(quail-defrule "/s" ?,L~)
(quail-defrule "/d" ?,L)

(quail-defrule "/Q" ?,L")
(quail-defrule "/W" ?,L#)
(quail-defrule "/E" ?,L$)
(quail-defrule "/R" ?,L%)
(quail-defrule "/T" ?,L&)
(quail-defrule "/Y" ?,L')
(quail-defrule "/U" ?,L()
(quail-defrule "/I" ?,L))
(quail-defrule "/O" ?,L*)
(quail-defrule "/P" ?,L+)
(quail-defrule "/A" ?,L,)
(quail-defrule "/S" ?,L.)
(quail-defrule "/D" ?,L/)
