;;; 92.8.8   created for Mule Ver.0.9.5 by T.Matsuzawa <mzw_t@yhp.hp.com>
;;; 92.12.28 modified for Mule ver.0.9.7 by Takahashi N. <ntakahas@etl.go.jp>
;;; 93.4.22  modified by Takahashi N. <ntakahas@etl.go.jp"
;;;          added "jis-greek".
(require 'quail)

(quail-define-package "jis-greek" "Ελληνικα" nil
		      "JIS X0208.1983 encoding.
The layout is same as greek, but uses JIS characters.
Sorry, accents and terminal sigma are not supported in JIS." nil t t t t)

(quail-defrule "1" ?１)
(quail-defrule "2" ?２)
(quail-defrule "3" ?３)
(quail-defrule "4" ?４)
(quail-defrule "5" ?５)
(quail-defrule "6" ?６)
(quail-defrule "7" ?７)
(quail-defrule "8" ?８)
(quail-defrule "9" ?９)
(quail-defrule "0" ?０)
(quail-defrule "-" ?−)
(quail-defrule "=" ?＝)
(quail-defrule "`" ?‘)
(quail-defrule "q" ?・)
(quail-defrule "w" ?σ)
(quail-defrule "e" ?ε)
(quail-defrule "r" ?ρ)
(quail-defrule "t" ?τ)
(quail-defrule "y" ?υ)
(quail-defrule "u" ?θ)
(quail-defrule "i" ?ι)
(quail-defrule "o" ?ο)
(quail-defrule "p" ?π)
(quail-defrule "[" ?［)
(quail-defrule "]" ?］)
(quail-defrule "a" ?α)
(quail-defrule "s" ?σ)
(quail-defrule "d" ?δ)
(quail-defrule "f" ?φ)
(quail-defrule "g" ?γ)
(quail-defrule "h" ?η)
(quail-defrule "j" ?ξ)
(quail-defrule "k" ?κ)
(quail-defrule "l" ?λ)
(quail-defrule ";" ?’)
(quail-defrule "'" ?’)
(quail-defrule "\\" ?＼)
(quail-defrule "z" ?ζ)
(quail-defrule "x" ?χ)
(quail-defrule "c" ?ψ)
(quail-defrule "v" ?ω)
(quail-defrule "b" ?β)
(quail-defrule "n" ?ν)
(quail-defrule "m" ?μ)
(quail-defrule "," ?, )
(quail-defrule "." ?. )
(quail-defrule "/" ?／)

(quail-defrule "!" ?！)
(quail-defrule "@" ?＠)
(quail-defrule "#" ?＃)
(quail-defrule "$" ?＃)
(quail-defrule "%" ?％)
(quail-defrule "^" ?＾)
(quail-defrule "&" ?＆)
(quail-defrule "*" ?＊)
(quail-defrule "(" ?（)
(quail-defrule ")" ?）)
(quail-defrule "_" ?＿)
(quail-defrule "+" ?＋)
(quail-defrule "~" ?￣)
(quail-defrule "Q" ?−)
(quail-defrule "W" ?Σ)
(quail-defrule "E" ?Ε)
(quail-defrule "R" ?Ρ)
(quail-defrule "T" ?Τ)
(quail-defrule "Y" ?Υ)
(quail-defrule "U" ?Θ)
(quail-defrule "I" ?Ι)
(quail-defrule "O" ?Ο)
(quail-defrule "P" ?Ρ)
(quail-defrule "{" ?｛)
(quail-defrule "}" ?｝)
(quail-defrule "A" ?Α)
(quail-defrule "S" ?Σ)
(quail-defrule "D" ?Δ)
(quail-defrule "F" ?Φ)
(quail-defrule "G" ?Γ)
(quail-defrule "H" ?Η)
(quail-defrule "J" ?Ξ)
(quail-defrule "K" ?Κ)
(quail-defrule "L" ?Λ)
(quail-defrule ":" ?”)
(quail-defrule "\"" ?”)
(quail-defrule "|" ?｜)
(quail-defrule "Z" ?Ζ)
(quail-defrule "X" ?Χ)
(quail-defrule "C" ?Ψ)
(quail-defrule "V" ?Ω)
(quail-defrule "B" ?Β)
(quail-defrule "N" ?Ν)
(quail-defrule "M" ?Μ)
(quail-defrule "<" ?；)
(quail-defrule ">" ?：)
(quail-defrule "?" ?？)

;;;

(quail-define-package "greek" ",FEkkgmij\" nil "Greek Keyboard
--------------

In the right of ,Fk key is a combination key, where
 ,F4 acute
 ,F( diaresis

e.g.
 ,Fa + ,F4 -> ,F\
 ,Fi + ,F( -> ,Fz
 ,Fi + ,F( + ,F4 -> ,F@
" nil t t t t)

;; 1!  2@  3#  4$  5%  6^  7&  8*  9(  0)  -_  =+  `~
;;  ,F7/  ,FrS  ,FeE  ,FqQ  ,FtT  ,FuU  ,FhH  ,FiI  ,FoO  ,FpP  [{  ]}
;;   ,FaA  ,FsS  ,FdD  ,FvV  ,FcC  ,FgG  ,FnN  ,FjJ  ,FkK  ,F4(  '"  \|
;;    ,FfF  ,FwW  ,FxX  ,FyY  ,FbB  ,FmM  ,FlL  ,;  .:  /?  

(quail-defrule "1" ?1)
(quail-defrule "2" ?2)
(quail-defrule "3" ?3)
(quail-defrule "4" ?4)
(quail-defrule "5" ?5)
(quail-defrule "6" ?6)
(quail-defrule "7" ?7)
(quail-defrule "8" ?8)
(quail-defrule "9" ?9)
(quail-defrule "0" ?0)
(quail-defrule "-" ?-)
(quail-defrule "=" ?=)
(quail-defrule "`" ?`)
(quail-defrule "q" ?,F7)
(quail-defrule "w" ?,Fr)
(quail-defrule "e" ?,Fe)
(quail-defrule "r" ?,Fq)
(quail-defrule "t" ?,Ft)
(quail-defrule "y" ?,Fu)
(quail-defrule "u" ?,Fh)
(quail-defrule "i" ?,Fi)
(quail-defrule "o" ?,Fo)
(quail-defrule "p" ?,Fp)
(quail-defrule "[" ?[)
(quail-defrule "]" ?])
(quail-defrule "a" ?,Fa)
(quail-defrule "s" ?,Fs)
(quail-defrule "d" ?,Fd)
(quail-defrule "f" ?,Fv)
(quail-defrule "g" ?,Fc)
(quail-defrule "h" ?,Fg)
(quail-defrule "j" ?,Fn)
(quail-defrule "k" ?,Fj)
(quail-defrule "l" ?,Fk)
(quail-defrule ";" ?,F4)
(quail-defrule "'" ?')
(quail-defrule "\\" ?\\)
(quail-defrule "z" ?,Ff)
(quail-defrule "x" ?,Fw)
(quail-defrule "c" ?,Fx)
(quail-defrule "v" ?,Fy)
(quail-defrule "b" ?,Fb)
(quail-defrule "n" ?,Fm)
(quail-defrule "m" ?,Fl)
(quail-defrule "," ?,)
(quail-defrule "." ?.)
(quail-defrule "/" ?/)

(quail-defrule "!" ?!)
(quail-defrule "@" ?@)
(quail-defrule "#" ?#)
(quail-defrule "$" ?$)
(quail-defrule "%" ?%)
(quail-defrule "^" ?^)
(quail-defrule "&" ?&)
(quail-defrule "*" ?*)
(quail-defrule "(" ?()
(quail-defrule ")" ?))
(quail-defrule "_" ?_)
(quail-defrule "+" ?+)
(quail-defrule "~" ?~)
(quail-defrule "Q" ?,F/)
(quail-defrule "W" ?,FS)
(quail-defrule "E" ?,FE)
(quail-defrule "R" ?,FQ)
(quail-defrule "T" ?,FT)
(quail-defrule "Y" ?,FU)
(quail-defrule "U" ?,FH)
(quail-defrule "I" ?,FI)
(quail-defrule "O" ?,FO)
(quail-defrule "P" ?,FP)
(quail-defrule "{" ?{)
(quail-defrule "}" ?})
(quail-defrule "A" ?,FA)
(quail-defrule "S" ?,FS)
(quail-defrule "D" ?,FD)
(quail-defrule "F" ?,FV)
(quail-defrule "G" ?,FC)
(quail-defrule "H" ?,FG)
(quail-defrule "J" ?,FN)
(quail-defrule "K" ?,FJ)
(quail-defrule "L" ?,FK)
(quail-defrule ":" ?,F()
(quail-defrule "\"" ?\")
(quail-defrule "|" ?|)
(quail-defrule "Z" ?,FF)
(quail-defrule "X" ?,FW)
(quail-defrule "C" ?,FX)
(quail-defrule "V" ?,FY)
(quail-defrule "B" ?,FB)
(quail-defrule "N" ?,FM)
(quail-defrule "M" ?,FL)
(quail-defrule "<" ?;)
(quail-defrule ">" ?:)
(quail-defrule "?" ??)

(quail-defrule "a;" ?,F\)
(quail-defrule "e;" ?,F])
(quail-defrule "h;" ?,F^)
(quail-defrule "i;" ?,F_)
(quail-defrule "o;" ?,F|)
(quail-defrule "y;" ?,F})
(quail-defrule "v;" ?,F~)
(quail-defrule "A;" ?,F6)
(quail-defrule "E;" ?,F8)
(quail-defrule "H;" ?,F9)
(quail-defrule "I;" ?,F:)
(quail-defrule "O;" ?,F<)
(quail-defrule "Y;" ?,F>)
(quail-defrule "V;" ?,F?)
(quail-defrule "i:" ?,Fz)
(quail-defrule "y:" ?,F{)
(quail-defrule "I:" ?,FZ)
(quail-defrule "Y:" ?,F[)
(quail-defrule "i:;" ?,F@)
(quail-defrule "y:;" ?,F`)
